apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "trivy-operator-polr-adapter.fullname" . }}
  labels:
    {{- include "trivy-operator-polr-adapter.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "trivy-operator-polr-adapter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "trivy-operator-polr-adapter.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "trivy-operator-polr-adapter.serviceAccountName" . }}
      automountServiceAccountToken: true
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          {{- if .Values.securityContext }}
          securityContext: {{ include "trivy-operator-polr-adapter.securityContext" . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --enable-vulnerability={{ .Values.adapters.vulnerabilityReports.enabled }}
            - --enable-config-audit={{ .Values.adapters.configAuditReports.enabled }}
            - --enable-kube-bench={{ .Values.adapters.cisKubeBenchReports.enabled }}
            - --enable-compliance={{ .Values.adapters.complianceReports.enabled }}
          readinessProbe:
            exec:
              command:
              - /app/trivy-operator-polr-adapter
              - version
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
